name: Node.js CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: dimensiondev/github-token-action@latest
        with:
          registry: true
      - run: npm cit
      - run: npm run lint
      - run: ./scripts/publish-to-github.sh
